[package]
name = "stravant/create-shared-toolbar"
description = "A utility function to create a Toolbar shared between multiple plugins."
version = "0.1.0"
license = "MIT"
authors = ["Mark Langen <stravant@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# None :)
